{...}:
{
  imports =
  [
    ./themes.nix
    ./applications.nix
    ./secrets.nix
    ./devices.nix
    ./workspace/polybar.nix
    ./workspace/i3.nix
    ./workspace/zsh.nix
    ./workspace/gtk.nix
    ./workspace/compton.nix
    ./workspace/emacs
    ./workspace/misc.nix
    ./workspace/dunst.nix
    ./workspace/albert
    ./workspace/kde.nix
  ];
}
