#!/usr/bin/env bash
[[ ! -f ./secret.nix ]] && echo null > secret.nix # if secret.nix doesn`t exist, create it
nixpkgs=$(nix eval --raw "(with import ./nix/sources.nix; nixpkgs)")
NIX_PATH=nixpkgs=$nixpkgs:nixos-config=./vm.nix nix build -f $nixpkgs/nixos vm
./result/bin/run-NixOS-VM-vm -m size=4G # Sorry, my apps are way too large

