// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "b0a9685e-f910-4393-a1a1-bf8e810a76e5");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1547241800);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1547242040);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1547241920);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1547241770);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{33a7ed8a-cbc8-4bcb-8aad-c19c2ecee2fc}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1547240400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1547241776220");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1547245376220");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1547241772");
user_pref("browser.slowStartup.averageTime", 1993);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20181231030024");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"urlbar-container\",\"downloads-button\",\"_372b19dc-789b-45ee-a817-90c405a7d37e_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"keepassxc-browser_keepassxc_org-browser-action\",\"_27c3c9d8-95cd-44e6-ae9c-ff537348b9f3_-browser-action\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"_372b19dc-789b-45ee-a817-90c405a7d37e_-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"keepassxc-browser_keepassxc_org-browser-action\",\"_27c3c9d8-95cd-44e6-ae9c-ff537348b9f3_-browser-action\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1547241774273");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "b1aee7fd9ce24a58a63bdbaa800aec43");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://discover/");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"bc467fbd-8906-40d6-b1bd-2a2f8ad656ac\",\"screenshots@mozilla.org\":\"9cbe2538-cb3c-442e-81ea-5df8f8eb4039\",\"webcompat-reporter@mozilla.org\":\"61e4a736-2687-4611-aa5b-5dde6c600dbd\",\"webcompat@mozilla.org\":\"a4796fd7-cb85-4b59-bb05-b4ba8ee3c352\",\"{372b19dc-789b-45ee-a817-90c405a7d37e}\":\"9e69a707-ed57-48a6-9ff4-a44d3fb5b2d5\",\"uBlock0@raymondhill.net\":\"05e92a52-23fd-4663-809b-55f40b591c6b\",\"keepassxc-browser@keepassxc.org\":\"3683d0a1-2fa1-48b0-8765-3bf9dadcd780\",\"{27c3c9d8-95cd-44e6-ae9c-ff537348b9f3}\":\"79930577-9260-4e43-bbaf-5ddf26642ae7\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1547241969);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181231030024");
user_pref("media.gmp-manager.lastCheck", 1547241967);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.cleaned-up", true);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "9015b016-8dfe-44ec-926f-3b1195b2487b");
user_pref("security.sandbox.plugin.tempDirSuffix", "d34db2c1-ed05-49cc-9ec9-951108ff03b5");
user_pref("services.blocklist.addons.checked", 1547241968);
user_pref("services.blocklist.gfx.checked", 1547241968);
user_pref("services.blocklist.onecrl.checked", 1547241968);
user_pref("services.blocklist.pinning.checked", 1547241968);
user_pref("services.blocklist.plugins.checked", 1547241968);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_update_seconds", 1547241968);
user_pref("services.settings.main.language-dictionaries.last_check", 1547241968);
user_pref("services.settings.main.onboarding.last_check", 1547241968);
user_pref("services.settings.main.sites-classification.last_check", 1547241968);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1547241769);
user_pref("toolkit.telemetry.cachedClientID", "568bee1a-0efa-4824-b4f4-0a2ee1646580");
user_pref("toolkit.telemetry.previousBuildID", "20181231030024");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
